import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DJ's Portfolio",
  description: "Generated by Next.js",
};

export default function Home() {
  return (
    <div className="relative z-0 bg-primary">
      <div className="bg-hero-pattern bg-cover bg-no-repeat bg-center">
        {/* <Hero /> */}
      </div>
      {/* <About /> */}
      {/* <Experience /> */}
      {/*<Tech />*/}
      {/*<Works />*/}
      {/*<Feedbacks />*/}
      <div className="relative z-0">
        {/* <Contact /> */}
        {/* <StarsCanvas /> */}
      </div>
    </div>
  );
}
